### ISSUE TITLE
Or Iam doing something wrong or the code is broken for the version of the game

### ISSUE THREAD

**Issue by Nextshot** [Halithor/BattleINF-Script-To-End-All-Script#2]
It seems that it dont work anyway
I literally just created an account, searched for a script after 10 mins understanding the game, throwed the
script into the 'script' tab and waited, nothing happened.

**Comment by Nextshot** [comment]
Iam aways doing it wrong, I think Iam a pest...
It needed a clean inventory to start the script... Why I dont tried that, dont bother about this.

**Comment by Halithor** [comment]
I wrote this script quite some time ago, so there's a really good chance that it's outdated at this point. As Battle INF is constantly being updated.

**Comment by Nextshot** [comment]
Nope, its isnt, works just fine, it was me that needed to empty the inventory first, as I said previously...
